server:
  port: 8084
spring:
  application:
    name: mg-gateway
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:654321@127.0.0.1:8081/eureka/
